# docker-compose.fish - docker completions for fish shell
#
# This file is generated by gen_docker_fish_completions.py from:
# https://github.com/barnybug/docker-fish-completion
#
# To install the completions:
# mkdir -p ~/.config/fish/completions
# cp docker-compose.fish ~/.config/fish/completions
#
# Completion supported:
# - parameters
# - commands
# - services

function __fish_docker_no_subcommand --description 'Test if docker has yet to be given the subcommand'
    for i in (commandline -opc)
        if contains -- $i build bundle config create down events exec help images kill logs pause port ps pull push restart rm run scale start stop top unpause up version
            return 1
        end
    end
    return 0
end

function __fish_print_docker_compose_services --description 'Print a list of docker-compose services'
    set -l composefiles
    getopts (commandline -o) | while read -l key value
        switch $key
            case "f"
                set composefiles $composefiles "-f" $value
            case "file"
                set composefiles $composefiles "-f" $value
        end
    end

    docker-compose $composefiles config --services ^/dev/null | command sort
end

# common options
complete -c docker-compose -n '__fish_docker_no_subcommand' -s f -l file -d u'Specify an alternate compose file (default: docker-compose.yml)'
complete -c docker-compose -n '__fish_docker_no_subcommand' -s p -l project-name -f -d u'Specify an alternate project name (default: directory name)'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l verbose -f -d u'Show more output'
complete -c docker-compose -n '__fish_docker_no_subcommand' -s v -l version -f -d u'Print version and exit'
complete -c docker-compose -n '__fish_docker_no_subcommand' -s H -l host -f -d u'Daemon socket to connect to'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l tls -f -d u'Use TLS; implied by --tlsverify'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l tlscacert -d u'Trust certs signed only by this CA'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l tlscert -d u'Path to TLS certificate file'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l tlskey -d u'Path to TLS key file'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l tlsverify -f -d u'Use TLS and verify the remote'
complete -c docker-compose -n '__fish_docker_no_subcommand' -l skip-hostname-check -f -d u"Don't check the daemon's hostname against the name specified"
complete -c docker-compose -n '__fish_docker_no_subcommand' -l project-directory -d u'Specify an alternate working directory'

# subcommands
# build
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a build -d u'Build or rebuild services'
complete -c docker-compose -A -n '__fish_seen_subcommand_from build' -l force-rm -f -d u'Always remove intermediate containers.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from build' -l no-cache -f -d u'Do not use cache when building the image.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from build' -l pull -f -d u'Always attempt to pull a newer version of the image.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from build' -l build-arg -f -d u'Set build-time variables for one service.'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from build' -a '(__fish_print_docker_compose_services)' -d "Service"

# bundle
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a bundle -d u'Generate a Docker bundle from the Compose file'
complete -c docker-compose -A -n '__fish_seen_subcommand_from bundle' -l push-images -f -d u'Automatically push images for any services'
complete -c docker-compose -A -n '__fish_seen_subcommand_from bundle' -s o -l output -d u'Path to write the bundle file to.'

# config
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a config -d u'Validate and view the Compose file'
complete -c docker-compose -A -n '__fish_seen_subcommand_from config' -l resolve-image-digests -f -d u'Pin image tags to digests.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from config' -s q -l quiet -f -d u"Only validate the configuration, don't print"
complete -c docker-compose -A -n '__fish_seen_subcommand_from config' -l services -f -d u'Print the service names, one per line.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from config' -l volumes -f -d u'Print the volume names, one per line.'

# create
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a create -d u'Create services'
complete -c docker-compose -A -n '__fish_seen_subcommand_from create' -l force-recreate -f -d u'Recreate containers even if their configuration and'
complete -c docker-compose -A -n '__fish_seen_subcommand_from create' -l no-recreate -f -d u"If containers already exist, don't recreate them."
complete -c docker-compose -A -n '__fish_seen_subcommand_from create' -l no-build -f -d u"Don't build an image, even if it's missing."
complete -c docker-compose -A -n '__fish_seen_subcommand_from create' -l build -f -d u'Build images before creating containers.'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from create' -a '(__fish_print_docker_compose_services)' -d "Service"

# down
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a down -d u'Stop and remove containers, networks, images, and volumes'
complete -c docker-compose -A -n '__fish_seen_subcommand_from down' -l rmi -f -d u'Remove images. Type must be one of:'
complete -c docker-compose -A -n '__fish_seen_subcommand_from down' -s v -l volumes -f -d u'Remove named volumes declared in the `volumes` section'
complete -c docker-compose -A -n '__fish_seen_subcommand_from down' -l remove-orphans -f -d u'Remove containers for services not defined in the'

# events
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a events -d u'Receive real time events from containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from events' -l json -f -d u'Output events as a stream of json objects'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from events' -a '(__fish_print_docker_compose_services)' -d "Service"

# exec
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a exec -d u'Execute a command in a running container'
complete -c docker-compose -A -n '__fish_seen_subcommand_from exec' -s d -f -d u'Detached mode: Run command in the background.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from exec' -l privileged -f -d u'Give extended privileges to the process.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from exec' -s u -l user -f -d u'Run the command as this user.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from exec' -s T -f -d u'Disable pseudo-tty allocation. By default `docker-compose exec`'
complete -c docker-compose -A -n '__fish_seen_subcommand_from exec' -l index=index -f -d u'index of the container if there are multiple'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from exec' -a '(__fish_print_docker_compose_services)' -d "Service"

# help
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a help -d u'Get help on a command'

# images
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a images -d u'List images'
complete -c docker-compose -A -n '__fish_seen_subcommand_from images' -s q -f -d u'Only display IDs'

# kill
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a kill -d u'Kill containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from kill' -s s -f -d u'SIGNAL to send to the container.'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from kill' -a '(__fish_print_docker_compose_services)' -d "Service"

# logs
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a logs -d u'View output from containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from logs' -l no-color -f -d u'Produce monochrome output.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from logs' -s f -l follow -f -d u'Follow log output.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from logs' -s t -l timestamps -f -d u'Show timestamps.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from logs' -l tail="all" -f -d u'Number of lines to show from the end of the logs'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from logs' -a '(__fish_print_docker_compose_services)' -d "Service"

# pause
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a pause -d u'Pause services'

# port
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a port -d u'Print the public port for a port binding'
complete -c docker-compose -A -n '__fish_seen_subcommand_from port' -l protocol=proto -f -d u'tcp or udp [default: tcp]'
complete -c docker-compose -A -n '__fish_seen_subcommand_from port' -l index=index -f -d u'index of the container if there are multiple'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from port' -a '(__fish_print_docker_compose_services)' -d "Service"

# ps
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a ps -d u'List containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from ps' -s q -f -d u'Only display IDs'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from ps' -a '(__fish_print_docker_compose_services)' -d "Service"

# pull
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a pull -d u'Pull service images'
complete -c docker-compose -A -n '__fish_seen_subcommand_from pull' -l ignore-pull-failures -f -d u'Pull what it can and ignores images with pull failures.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from pull' -l parallel -f -d u'Pull multiple images in parallel.'

# push
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a push -d u'Push service images'
complete -c docker-compose -A -n '__fish_seen_subcommand_from push' -l ignore-push-failures -f -d u'Push what it can and ignores images with push failures.'

# restart
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a restart -d u'Restart services'
complete -c docker-compose -A -n '__fish_seen_subcommand_from restart' -s t -l timeout -f -d u'Specify a shutdown timeout in seconds.'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from restart' -a '(__fish_print_docker_compose_services)' -d "Service"

# rm
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a rm -d u'Remove stopped containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from rm' -s f -l force -f -d u"Don't ask to confirm removal"
complete -c docker-compose -A -n '__fish_seen_subcommand_from rm' -s s -l stop -f -d u'Stop the containers, if required, before removing'
complete -c docker-compose -A -n '__fish_seen_subcommand_from rm' -s v -f -d u'Remove any anonymous volumes attached to containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from rm' -s a -l all -f -d u'Deprecated - no effect.'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from rm' -a '(__fish_print_docker_compose_services)' -d "Service"

# run
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a run -d u'Run a one-off command'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s d -f -d u'Detached mode: Run container in the background, print'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -l name -f -d u'Assign a name to the container'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -l entrypoint -f -d u'Override the entrypoint of the image.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s e -f -d u'Set an environment variable (can be used multiple times)'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s u -l user="" -f -d u'Run as specified username or uid'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -l no-deps -f -d u"Don't start linked services."
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -l rm -f -d u'Remove container after run. Ignored in detached mode.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s p -l publish=[] -f -d u"Publish a container's port(s) to the host"
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -l service-ports -f -d u"Run command with the service's ports enabled and mapped"
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s v -l volume=[] -f -d u'Bind mount a volume (default [])'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s T -f -d u'Disable pseudo-tty allocation. By default `docker-compose run`'
complete -c docker-compose -A -n '__fish_seen_subcommand_from run' -s w -l workdir="" -f -d u'Working directory inside the container'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from run' -a '(__fish_print_docker_compose_services)' -d "Service"

# scale
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a scale -d u'Set number of containers for a service'
complete -c docker-compose -A -n '__fish_seen_subcommand_from scale' -s t -l timeout -f -d u'Specify a shutdown timeout in seconds.'

# start
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a start -d u'Start services'

# stop
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a stop -d u'Stop services'
complete -c docker-compose -A -n '__fish_seen_subcommand_from stop' -s t -l timeout -f -d u'Specify a shutdown timeout in seconds.'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from stop' -a '(__fish_print_docker_compose_services)' -d "Service"

# top
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a top -d u'Display the running processes'

# unpause
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a unpause -d u'Unpause services'

# up
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a up -d u'Create and start containers'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -s d -f -d u'Detached mode: Run containers in the background,'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l no-color -f -d u'Produce monochrome output.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l no-deps -f -d u"Don't start linked services."
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l force-recreate -f -d u'Recreate containers even if their configuration'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l no-recreate -f -d u"If containers already exist, don't recreate them."
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l no-build -f -d u"Don't build an image, even if it's missing."
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l build -f -d u'Build images before starting containers.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l abort-on-container-exit -f -d u'Stops all containers if any container was stopped.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -s t -l timeout -f -d u'Use this timeout in seconds for container shutdown'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l remove-orphans -f -d u'Remove containers for services not'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l exit-code-from -f -d u'Return the exit code of the selected service container.'
complete -c docker-compose -A -n '__fish_seen_subcommand_from up' -l scale -f -d u'Scale SERVICE to NUM instances. Overrides the `scale`'
complete -c docker-compose -A -f -n '__fish_seen_subcommand_from up' -a '(__fish_print_docker_compose_services)' -d "Service"

# version
complete -c docker-compose -f -n '__fish_docker_no_subcommand' -a version -d u'Show the Docker-Compose version information'
complete -c docker-compose -A -n '__fish_seen_subcommand_from version' -l short -f -d u"Shows only Compose's version number."
